services:
  app:
    build: src
    ports:
      - 8009:1337
    environment:
      REDIS_URL: redis://db:6379
      SECRET_TOKEN: DO_NOT_GO_GENTLE_INTO_THAT_GOOD_NIGHT_5612780561278
      SERVER_PORT: 1337
      FLAG: MINUTEMAN{T4RS_D1D_N0T_4CC0UNT_4_URL_3NC0D1NG}
    restart: always
  db:
    image: redis:latest
    restart: always