services:
  backend:
    restart: always
    build: .
    ports:
      - 8004:3000
    environment:
      REDIS_URL: redis://cache-storage:6379
      REDIS_HOST: cache-storage
      FLAG: MINUTEMAN{wELl_f1Nd_A_w@y_w3_alW@yS_h@v3}
  cache-storage:
    image: redis:latest
    restart: always
