services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    network_mode: bridge

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-node-app-container
    restart: always
    ports:
      - "8005:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_TOKEN=DAY_ONE_CORNFIELD_CHASE_2095732
      - FLAG=MINUTEMAN{i_H@t3_fR0nT3nD!}
    links:
      - redis
    network_mode: bridge
